### ISSUE TITLE
Provide useful information when a Bugzilla bug number is mentioned

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/webqabot#1]
When a Bugzilla bug number is mentioned in the channel, the bot should provide a link to the bug, the importance, status, assignee, and summary.

Example conversation:
> davehunt: Hey Bob, check out bug 689423
> webqabot: Bug https://bugzilla.mozilla.org/show_bug.cgi?id=689423 normal, NEW , Add Angry Birds to Firefox new tab page

Let's try to write this as an external script so that other users of Hubot can use it. This will require at least a way to configure the Bugzilla instance to query.

**Comment by bobsilverberg** [comment]
It looks like the code in https://github.com/agiledigital/hubot-jirabot might do something similar, so might be worth looking at.

**Comment by davehunt** [comment]
Also, we've implemented this before, here: https://github.com/mozilla/mozwebqa-bot/blob/a996fba3a5cd61837cd712b4caaa1a1a1b7cc81b/bot.js#L141
