### ISSUE TITLE
Enhance the meeting announcement to include a link to the current week's meeting notes

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/webqabot#23]
The url to the notes should be https://wiki.mozilla.org/QA/Execution/Web_Testing/Meetings/{current_date}, where {current_date} should be in the format of YYYY-MM-DD.

**Comment by MonicaG** [comment]
Hi @bobsilverberg - I am going to attempt this task.  I haven't worked on a bot before and it sounds interesting.

**Comment by bobsilverberg** [comment]
Sounds good, @MonicaG. Let me know if you have any questions. I'd like to invite you to our Web QA Enthusiasts team [1], which will allow me to assign this issue to you. I don't seem to have access to do that, but I'll ask someone else to help me with that, so expect an invitation in the next few days.

Thanks and good luck!

[1] https://github.com/orgs/mozilla/teams/web-qa-enthusiasts

**Comment by MonicaG** [comment]
@bobsilverberg - sounds good!  I do have a few questions about this task:

1) Are the wiki and the chat server in the same timezone?  I'm wondering if I need to consider the case where the webqabot will think it's one date/time and the wiki another date/time; which could result in webqabot listing a link that is not valid.  

2) Is a message like the following ok:
View the current week's meeting notes at: https://wiki.mozilla.org/QA/Execution/Web_Testing/Meetings/#{current_date}

3) Related to issue #18 - do you guys have any thoughts on a testing framework for this project.  I was thinking about writing a unit test for the code that will format the date appropriately.  It looks like [hubot tests use mocha](https://github.com/github/hubot/blob/master/package.json#L28) 

Thanks!

**Comment by bobsilverberg** [comment]
On Fri, Dec 4, 2015 at 10:23 AM, Monica Granbois <notifications@github.com>
wrote:

> @bobsilverberg <https://github.com/bobsilverberg> - sounds good! I do
> have a few questions about this task:
>
> 1) Are the wiki and the chat server in the same timezone? I'm wondering if
> I need to consider the case where the webqabot will think it's one
> date/time and the wiki another date/time; which could result in webqabot
> listing a link that is not valid.
>
I'm not entirely sure which timezone the server runs in, but I think we
only want to change the meeting announcement when it is made specifically,
as opposed to the general response to the command `meeting` which starts
with `Come join us at 9am Pacific every Thursday for our team meeting!`. If
we only want to add a link to specific meeting notes when an announcement
is being made, I think it's safe to assume that the date to use is the
current date.

2) Is a message like the following ok:
> View the current week's meeting notes at:
> https://wiki.mozilla.org/QA/Execution/Web_Testing/Meetings/#{current_date}
>
I think you can keep the existing text, which is `Meeting notes are
available at
https://wiki.mozilla.org/QA/Execution/Web_Testing#Meeting_Notes`, but just
use the correct specific link to the notes for the current meeting.

3) Related to issue #18 <https://github.com/mozilla/webqabot/issues/18> -
> do you guys have any thoughts on a testing framework for this project. I
> was thinking about writing a unit test for the code that will format the
> date appropriately. It looks like hubot tests use mocha
> <https://github.com/github/hubot/blob/master/package.json#L28>
>
> I don't think any of us have put much thought into this. I believe that
both @davehunt and I took a quick look at what it would take to add tests,
but neither of us got anywhere with it as it's new to both of us as well.
So please feel free to try out anything that works for you. I look forward
to seeing what you come up with.

**Comment by MonicaG** [comment]
@bobsilverberg thank you for the reply!  
I was thinking of starting on #18 first and then come back to this one. My thoughts being I would like to unit test my change, so maybe #18 should be the place to start.

I was thinking I would check to see what other mozilla javascript projects use for unit testing.  From there I would see what the top 2 frameworks are (if there is any kind of consensus) and try them out.  Does this approach sound alright to you?

**Comment by bobsilverberg** [comment]
That does sound like a good approach, @MonicaG. You might also want to look at existing approaches that other people have used with Hubot. Let me know if you have any questions or need any help, and thanks!

**Comment by MonicaG** [comment]
Hi @bobsilverberg,

I'm going to do this one next.  I just need a bit of clarification. Is the https://wiki.mozilla.org/QA/Execution/Web_Testing/Meetings/{current_date} link only to be displayed when the 'announceMeeting' event is triggered from the [cron-jobs.coffee](https://github.com/mozilla/webqabot/blob/master/scripts/cron-jobs.coffee) file?

**Comment by bobsilverberg** [comment]
@MonicaG I guess that makes sense. Otherwise we wouldn't know the correct date to use for the agenda. On the other hand, it would be nice if we could also issue the command ourselves, but we wouldn't want the notes to display if we were telling people about a meeting that wasn't happening today. Can you think of a good way to deal with all of those cases?

**Comment by davehunt** [comment]
Why don't we just use the date of the next meeting? We can either make the relatively safe assumption that it's every Thursday, or if we want to be clever we could somehow use the [public calendar entry](https://calendar.google.com/calendar/render?eid=cnZwaXNjdXJobWM4dHF2M2tsbDFqc2JhMmdfMjAxNjAxMjhUMTcwMDAwWiBtb3ppbGxhLmNvbV82NG5rYnI2MmRqYTg1NW9qbXNuamkyODI3OEBn&ctz=America/Los_Angeles&sf=true&output=xml#eventpage_6)

**Comment by MonicaG** [comment]
Sorry, I'm being a bit dense in understanding what is to be done. 

Currently there are 2 meeting announcements.

1) The case where the bot emits 'announceMeeting' from the cron job.  The message displayed is:
 
>Come join us in 15 minutes for our team meeting!  Meeting notes are available at https://wiki.mozilla.org/QA/Execution/Web_Testing#Meeting_Notes
Our Vidyo room is WebQA (8824)
Public link: https://v.mozilla.com/flex.html?roomdirect.html&key=Tc08xVjMQmaVscjhN5jlm7mDknY
Joining by phone: https://wiki.mozilla.org/Teleconferencing#Dialing_In
For information on Vidyo: https://wiki.mozilla.org/Vidyo

2) The case where the user asks webqabot "meeting". The message displayed is:

>Come join us at 9am Pacific every Thursday for our team meeting!  Meeting notes are available at https://wiki.mozilla.org/QA/Execution/Web_Testing#Meeting_Notes
Our Vidyo room is WebQA (8824)
Public link: https://v.mozilla.com/flex.html?roomdirect.html&key=Tc08xVjMQmaVscjhN5jlm7mDknY
Joining by phone: https://wiki.mozilla.org/Teleconferencing#Dialing_In
For information on Vidyo: https://wiki.mozilla.org/Vidyo

The following is my understanding of the updates:

For case 1, we want to change the link from https://wiki.mozilla.org/QA/Execution/Web_Testing#Meeting_Notes 
to 
https://wiki.mozilla.org/QA/Execution/Web_Testing/Meetings/{current_date}

Is that correct?

For case 2 there are two scenarios:
a) if the "meeting" command is issued by a user on the meeting day (Thursday) then display the text from case 2 but with the link https://wiki.mozilla.org/QA/Execution/Web_Testing/Meetings/{current_date}  So, it would look like this:
>Come join us at 9am Pacific every Thursday for our team meeting!  Meeting notes are available at https://wiki.mozilla.org/QA/Execution/Web_Testing/Meetings/{current_date}
Our Vidyo room is WebQA (8824)
Public link: https://v.mozilla.com/flex.html?roomdirect.html&key=Tc08xVjMQmaVscjhN5jlm7mDknY
Joining by phone: https://wiki.mozilla.org/Teleconferencing#Dialing_In
For information on Vidyo: https://wiki.mozilla.org/Vidyo


b) if the meeting command is issued by a user on a day that is not the meeting day (not a Thursday), then display the text and link as is. 
>Come join us at 9am Pacific every Thursday for our team meeting!  Meeting notes are available at https://wiki.mozilla.org/QA/Execution/Web_Testing#Meeting_Notes
Our Vidyo room is WebQA (8824)
Public link: https://v.mozilla.com/flex.html?roomdirect.html&key=Tc08xVjMQmaVscjhN5jlm7mDknY
Joining by phone: https://wiki.mozilla.org/Teleconferencing#Dialing_In
For information on Vidyo: https://wiki.mozilla.org/Vidyo

Is that correct?

And also, look into using the public calendar entry vs hardcoding the Thursday meeting rule.

Thanks!

**Comment by davehunt** [comment]
We can just get the date of the upcoming meeting based on the assumption that it's either today (if Thursday) or next Thursday. Then we just include that date in the meeting notes URL for all responses.

**Comment by davehunt** [comment]
We _could_ tweak the response to say "Today's meeting notes are available..." and "Upcoming meeting notes are available..." but I don't know if that's really needed.
