### ISSUE TITLE
Add lmgtfy command (let me google that for you)

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/webqabot#3]
Example conversation:
> davehunt: webqabot: lmgtfy what's the best web browser?
> webqabot: davehunt: http://lmgtfy.com/?q=what%27s+the+best+web+browser%3F

I think this would make sense as an external script that we can depend on, but it could start out as an internal script.

**Comment by bobsilverberg** [comment]
For anyone interested in working on this task, a snippet of code that would work to provide this functionality is:

```javascript
  robot.respond /lmgtfy (.*)/i, (res) ->
    topic = encodeURIComponent(res.match[1]).replace(/[!'()*]/g, escape)
    res.send "http://lmgtfy.com/?q=#{topic}"
```

**Comment by davehunt** [comment]
We decided not to fix this in #12 so it's still open if anyone wants to work on it.

**Comment by MonicaG** [comment]
Hi,
A couple of questions about this one:

- There is an existing [lmgtfy.coffee](https://github.com/github/hubot-scripts/blob/master/src/scripts/lmgtfy.coffee) script in the [hubot-scripts](https://github.com/github/hubot-scripts) repo.  Should I use that?  One concern is the hubot-scripts repo is deprecated as external scripts are now to be released as a npm package. I checked [npm for hubot scripts](https://www.npmjs.com/browse/keyword/hubot-scripts) and did not see a lmgtfy package.  

- If not using the script from hubot-scripts, there was some discussion in #12 on whether a lmgtfy script should be in its own file or not.  Was there any descision on whether this command should be added to it's own file or to the existing webqa.coffee script?

Thanks!

**Comment by davehunt** [comment]
Hey @MonicaG. If I recall correctly @m8ttyB was the one to suggest this feature, so perhaps he can help. Personally I think the best approach would be to develop a lmgtfy external script and release it as an npm package that webqabot can then simply require.

**Comment by MonicaG** [comment]
Hi @davehunt and @m8ttyB, is there a repo where you would like me to create the lmgtfy script?

**Comment by davehunt** [comment]
@MonicaG feel free to create it under your own Github account.
