### ISSUE TITLE
Welcome new people to the channel

### ISSUE THREAD

**Issue by davehunt** [mozilla/webqabot#4]
The bot should welcome people to the channel if they've not been seen or welcomed before. In the simplest form we should just make sure we persist nicks that have been seen and only welcome newcomers. We could be smarter and store nick changes, and ignore similar nicks (such as davehunt and davehunt|offline), we could also consider only welcoming people if they have not been addressed by someone else within a reasonable time.

Example converstation:

> newbie has joined (newbie@random.ip)
webqabot: Hey newbie, welcome to our channel! If you want to know more about our team, visit https://quality.mozilla.org/teams/web-qa/

We should also be able to prompt the bot to welcome someone:

> davehunt: webqabot: welcome newbie
webqabot: Hey newbie, welcome to our channel! If you want to know more about our team, visit https://quality.mozilla.org/teams/web-qa/

The nick could also be optional:

> davehunt: webqabot: welcome
webqabot: Hey davehunt, welcome to our channel! If you want to know more about our team, visit https://quality.mozilla.org/teams/web-qa/

I think this could make sense as an external script, which could take the welcome message as part of the configuration.

**Comment by bobsilverberg** [comment]
This was partially addresses in https://github.com/mozilla/webqabot/commit/7c8056e6ac4295adcf765f76a0180c94018de2cd. The first example, of welcoming people when they join the channel, has been addressed, but the ability to manually trigger the welcome message has not. Do we feel that needs to be added? I kind of feel like if there is someone in the room who is in a position to trigger the welcome, they might as well personally welcome the user.

What do you think, @davehunt?

**Comment by davehunt** [comment]
It was a feature request that came up during our team meetings. It's possible that someone that has been in the channel before missed or needs reminding of the content in the welcome message. I think it's a reasonable feature to have, but we could split it out into another issue that doesn't block 1.0. I suppose it really should be tracked against hubot-welcome.

**Comment by bobsilverberg** [comment]
Indeed (re: it should be an issue against hubot-welcome), although I'm still -1 on the feature. Certainly the current content of the welcome message isn't particularly useful, and I really think that if someone is going to take the time to ask hubot to welcome a user they should just welcome the user themself. I think it would actually come across as unfriendly to ask a robot to welcome someone when you could just do it yourself.

**Comment by davehunt** [comment]
I see your point, especially given the current content of the welcome message, however this message is likely to change and contain more resources. Being able to just type `welcome` instead of remembering the details of the welcome message would be a convenience.

**Comment by bobsilverberg** [comment]
True, but I still don't like it. Feel free to open an issue against `hubot-welcome` if you wish, at which point I think we can close this issue.

**Comment by davehunt** [comment]
I raised https://github.com/bobsilverberg/hubot-welcome/issues/1
