### ISSUE TITLE
Announce reminders for weekly team meetings

### ISSUE THREAD

**Issue by davehunt** [mozilla/webqabot#5]
We'd like the bot to announce reminders for our weekly team meetings. One idea would be to hook into our public calendar, however this is probably a rather advanced approach. Alternatively we could just maintain a schedule using one of the hubot cron scripts.

Example conversation:
> **webqabot**: Come join us in 15 minutes for our team meeting!
**webqabot**: Meeting notes are available at https://wiki.mozilla.org/QA/Execution/Web_Testing#Meeting_Notes
**webqabot**: Our Vidyo room is WebQA (8824)
**webqabot**: Public link: https://v.mozilla.com/flex.html?roomdirect.html&key=Tc08xVjMQmaVscjhN5jlm7mDknY
**webqabot**: Joining by phone: https://wiki.mozilla.org/Teleconferencing#Dialing_In
**webqabot**: For information on Vidyo: https://wiki.mozilla.org/Vidyo

**Comment by bobsilverberg** [comment]
This was fixed in https://github.com/mozilla/webqabot/commit/2114a1416a2938b00c471a77661aa64e31a7cb42
