### ISSUE TITLE
Update the readme for the bot

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/webqabot#8]
Remove most of the boilerplate that was added about Hubot and just provide a link to Hubot (i.e., https://hubot.github.com/).

Add information about how to deploy the bot to Heroku, including the environment variables that need to be set.
Add information about how to create webhooks for GitHub repositories to be watched for issues, pull requests and pushes.

**Comment by MonicaG** [comment]
Hi @bobsilverberg 
Is there anything left to do on this issue?  It looks like it is done.
Monica

**Comment by bobsilverberg** [comment]
I think this can be closed. @davehunt?

**Comment by davehunt** [comment]
I agree. Closing!
